ALTER TABLE employees 
ADD COLUMN IF NOT EXISTS ktp_number TEXT,
ADD COLUMN IF NOT EXISTS bpjs_kesehatan TEXT,
ADD COLUMN IF NOT EXISTS bpjs_ketenagakerjaan TEXT,
ADD COLUMN IF NOT EXISTS marital_status TEXT,
ADD COLUMN IF NOT EXISTS emergency_contacts JSONB,
ADD COLUMN IF NOT EXISTS work_history JSONB,
ADD COLUMN IF NOT EXISTS bank_account JSONB,
ADD COLUMN IF NOT EXISTS is_profile_completed BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS verified_by TEXT,
ADD COLUMN IF NOT EXISTS verified_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS is_locked BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS managed_unit_id TEXT;
